// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebGioiThieuAmThuc.Data;

#nullable disable

namespace WebGioiThieuAmThuc.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favorite_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("specialty_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__46ACF4CBC5790764");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex(new[] { "UserId" }, "IX_Favorites_User");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating1")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("specialty_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RatingId")
                        .HasName("PK__Ratings__D35B278B0D6589A6");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "SpecialtyId" }, "IX_Ratings_Specialty");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("region_name");

                    b.HasKey("RegionId")
                        .HasName("PK__Regions__01146BAE6E3C8104");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("specialty_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("approved")
                        .HasColumnName("status");

                    b.HasKey("SpecialtyId")
                        .HasName("PK__Specialt__B90D8D12B226448A");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "RegionId" }, "IX_Specialties_Region");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F0BC353E0");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E6164E0CEB30B")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__F3DBC572A191AE1E")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.Favorite", b =>
                {
                    b.HasOne("WebGioiThieuAmThuc.Models.Specialty", "Specialty")
                        .WithMany("Favorites")
                        .HasForeignKey("SpecialtyId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorites_Specialties");

                    b.HasOne("WebGioiThieuAmThuc.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorites_Users");

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.Rating", b =>
                {
                    b.HasOne("WebGioiThieuAmThuc.Models.Specialty", "Specialty")
                        .WithMany("Ratings")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Specialties");

                    b.HasOne("WebGioiThieuAmThuc.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Users");

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.Specialty", b =>
                {
                    b.HasOne("WebGioiThieuAmThuc.Models.User", "CreatedByNavigation")
                        .WithMany("Specialties")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Specialties_Users");

                    b.HasOne("WebGioiThieuAmThuc.Models.Region", "Region")
                        .WithMany("Specialties")
                        .HasForeignKey("RegionId")
                        .IsRequired()
                        .HasConstraintName("FK_Specialties_Regions");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.Region", b =>
                {
                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.Specialty", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("WebGioiThieuAmThuc.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Ratings");

                    b.Navigation("Specialties");
                });
#pragma warning restore 612, 618
        }
    }
}
